### ISSUE TITLE
新家装通App

### ISSUE THREAD

**Issue by giscafer** [giscafer/project#2]
### 技术栈

- 框架：ionic3
- 后端：Java

- 开发周期：22天完成开发与测试并上线
- 开发参与人数：6人（岗位角色：2个android开发，1个IOS开发，3个前端开发人员）
- 本人项目角色：项目负责人、开发负责人

### 总结

短周期内保证质量并能上线，大家都很给力。开发的过程中也学习熟悉了ionic3；短周期内上线同时也充分说明ionic3，web开发的模式，开发效率确实比原生开发高。使用开发框架做他们最擅长的事就很高效，不管是Ionic还是RN，还是原生方式，都有他们自己擅长的地方。

### 压缩图gif（页面样式效果失真）

![jzt_compress](https://user-images.githubusercontent.com/8676711/28448800-818ad442-6e0d-11e7-9ddb-0842927a1bbb.gif)

### 清晰图gif（10M）

https://raw.githubusercontent.com/giscafer/project/master/screenshot/demo/jzt.gif

**Comment by giscafer** [comment]
App store https://itunes.apple.com/cn/app/id1257685721

**Comment by dianxiaopao** [comment]
新家装通App 开源的吗？源码在哪？

**Comment by giscafer** [comment]
@dianxiaopao 公司产品，不会开源
